package model

var (

	//P2P
	NETWORK_LIST      = "NETWORK_LIST"
	NETWORK_STATE     = "NETWORK_STATE"
	REQUEST_NET_STATE = "REQUEST_NET_STATE"
	PEER              = "PEER"
	GET_PEER          = "GET_PEER"

	PEER_LIST     = "PEER_LIST"
	GET_PEER_LIST = "GET_PEER_LIST"

	MESSAGE = "MESSAGE"

	//P2P BLOCK
	COMMIT      = "COMMIT"
	APPROVE     = "APPROVE"
	DECLINE     = "DECLINE"
	BLOCK       = "BLOCK"
	GET_BLOCK   = "GET_BLOCK"
	TRANSACTION = "TRANSACTION"
)
